# Generated by Django 5.0.4 on 2024-09-11 20:05

import Account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('role', models.CharField(choices=[('CSO', 'CSO'), ('SDM', 'SDM'), ('BC', 'BC'), ('FM', 'FM'), ('FINANCE', 'FINANCE'), ('AGENAFINANCE', 'AGENAFINANCE'), ('LOGISTIC', 'LOGISTIC'), ('GM', 'GM'), ('Clerk', 'Clerk'), ('AdissAbabaInventory', 'AdissAbabaInventory'), ('AgenaInventory', 'AgenaInventory'), ('ProductionInventory', 'ProductionInventory'), ('Inventory', 'Inventory'), ('Supervisior', 'Supervisior'), ('superAdmin', 'superAdmin')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='staff_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='staff_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebCustomer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_route', models.CharField(choices=[('Area1', 'Area1'), ('Area1B', 'Area1B'), ('Area2', 'Area2'), ('Area3', 'Area3'), ('EastMarket', 'EastMarket'), ('AdissAbabaMarket', 'AdissAbabaMarket'), ('AdissAbabaMarket2', 'AdissAbabaMarket2'), ('Area8', 'Area8'), ('Area1DirectSales', 'Area1DirectSales'), ('AdissAbabaMarket', 'AdissAbabaMarket')], max_length=255)),
                ('tin_number', models.CharField(blank=True, max_length=255, null=True)),
                ('tin_number_doc', models.FileField(blank=True, null=True, upload_to=Account.models.customer_file_path)),
                ('business_license_no', models.CharField(blank=True, max_length=255, null=True)),
                ('business_license_no_doc', models.FileField(blank=True, null=True, upload_to=Account.models.customer_file_path)),
                ('business_registration_no', models.CharField(blank=True, max_length=255, null=True)),
                ('business_registration_no_doc', models.FileField(blank=True, null=True, upload_to=Account.models.customer_file_path)),
                ('sales_target', models.CharField(blank=True, max_length=255, null=True)),
                ('gps_coordinates', models.CharField(blank=True, max_length=255, null=True)),
                ('ledger', models.IntegerField(blank=True, default=0, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_credit', models.BooleanField(default=False)),
                ('credit_limit', models.IntegerField(blank=True, default=0, null=True)),
                ('contact_information', models.CharField(blank=True, max_length=255, null=True)),
                ('is_cell', models.BooleanField(blank=True, default=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='webcustomer_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='webcustomer_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebCustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger', models.CharField(blank=True, max_length=255, null=True)),
                ('Phone', models.TextField(blank=True, max_length=255, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.webcustomer')),
            ],
        ),
    ]
