# Generated by Django 5.0.4 on 2024-09-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webcustomer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='webcustomer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='webcustomer',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='staff',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='staff_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='staff_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='webcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
