# Generated by Django 5.0.4 on 2024-09-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_remove_webcustomer_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='web_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('CSO', 'CSO'), ('SDM', 'SDM'), ('BC', 'BC'), ('FM', 'FM'), ('FINANCE', 'FINANCE'), ('AGENAFINANCE', 'AGENAFINANCE'), ('LOGISTIC', 'LOGISTIC'), ('GM', 'GM'), ('Clerk', 'Clerk'), ('AdissAbabaInventory', 'AdissAbabaInventory'), ('AgenaInventory', 'AgenaInventory'), ('ProductionInventory', 'ProductionInventory'), ('Inventory', 'Inventory'), ('Supervisior', 'Supervisior'), ('Agent', 'Agent'), ('superAdmin', 'superAdmin')], max_length=100),
        ),
    ]
