# Generated by Django 5.0.4 on 2024-09-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_staff_is_web_staff_web_id_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcustomer',
            name='is_cell',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
